name: Auto release
description: Tag and relase if commits from a given author.
author: Adevinta

inputs:

  author:
    description: Author
    type: string
    required: false
    default: dependabot[bot]

outputs:
  new-tag:
    value: ${{ steps.scan.history.next }}
    description: Created tag

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'  # Requires the full history to calculate the tag
    - name: Get commit history info since last tag
      id: history
      shell: bash
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 || true)
        if [ -z "$LAST_TAG" ]; then
            echo "No tags found, skipping"
            exit 0
        fi
        AUTHORS=$(git log $LAST_TAG..HEAD --pretty=format:"%an" | sort | uniq)
        if [ "$AUTHORS" == "" ]; then
            echo "No commits since last tag"
            exit 0
        fi
        # this should be improved or delegated to anothrNick/github-tag-action or similar.
        RE='^v\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)$'
        MAJOR=$(echo $LAST_TAG | sed -e "s#$RE#\1#")
        MINOR=$(echo $LAST_TAG | sed -e "s#$RE#\2#")
        PATCH=$(echo $LAST_TAG | sed -e "s#$RE#\3#")
        NEXT="v$MAJOR.$MINOR.$((PATCH+1))"
        {
          echo 'authors<<EOF' && echo "$AUTHORS" && echo EOF
          echo "last=$LAST_TAG"
          echo "next=$NEXT"
        } >> "$GITHUB_OUTPUT"
    - name: Create tag and release
      if: ${{steps.history.outputs.authors==inputs.author && steps.history.outputs.next!=''}}
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        gh release create "${{steps.history.outputs.next}}" --generate-notes
