name: Approve

on:
  workflow_call:
    inputs:
      author:
        required: false
        type: string
        default: dependabot[bot]
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
jobs:
  approve:
    runs-on: ${{ inputs.runs-on }}
    if: ${{ github.actor == inputs.author }}
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.DEPENDABOT_AUTOMERGE_TOKEN}}
    steps:
    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
    - name: approve and merge
      if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
      run: |
        gh pr review --approve "$PR_URL"
        gh pr merge --auto --squash --delete-branch "$PR_URL"
